#:schema node_modules/wrangler/config-schema.json
name = "supermemory-web"
compatibility_date = "2025-03-12"
pages_build_output_dir = "./build/client"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "METADATA_KV"
id = "d1ab2121c97248e08e28adb0a939282f"

[[kv_namespaces]]
binding = "ENCRYPTED_TOKENS"
id = "62a7415a6e8f4ee2bdc0b308c3666838"
preview_id = "62a7415a6e8f4ee2bdc0b308c3666838"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "supermemory-images"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "51da5594ec86434c8c2375c15935440c"
localConnectionString = "postgresql://postgres:@Gmail12345@db.sdohppbkaordjydyhwqf.supabase.co:5432/postgres"

[placement]
mode = "smart"
